"""Init Database

Revision ID: bc7abf5ec1f4
Revises: 
Create Date: 2024-05-14 15:16:35.937829

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'bc7abf5ec1f4'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('blacklist',
    sa.Column('token', sa.String(length=500), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_blacklist_id'), 'blacklist', ['id'], unique=False)
    op.create_index(op.f('ix_blacklist_token'), 'blacklist', ['token'], unique=True)
    op.create_table('category',
    sa.Column('name', sa.String(length=50), nullable=False),
    sa.Column('slug', sa.String(length=50), nullable=False),
    sa.Column('description', sa.String(length=255), nullable=True),
    sa.Column('count', sa.Integer(), nullable=False),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_category_id'), 'category', ['id'], unique=False)
    op.create_table('cruitment_demand',
    sa.Column('key', sa.String(length=50), nullable=False),
    sa.Column('value', sa.Integer(), nullable=False),
    sa.Column('time_scan', sa.DateTime(timezone=True), nullable=False),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_cruitment_demand_id'), 'cruitment_demand', ['id'], unique=False)
    op.create_table('field',
    sa.Column('name', sa.String(length=50), nullable=False),
    sa.Column('slug', sa.String(length=50), nullable=False),
    sa.Column('description', sa.String(length=255), nullable=True),
    sa.Column('count', sa.Integer(), nullable=False),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_field_id'), 'field', ['id'], unique=False)
    op.create_table('group_position',
    sa.Column('name', sa.String(length=50), nullable=False),
    sa.Column('slug', sa.String(length=50), nullable=False),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_group_position_id'), 'group_position', ['id'], unique=False)
    op.create_index(op.f('ix_group_position_name'), 'group_position', ['name'], unique=False)
    op.create_index(op.f('ix_group_position_slug'), 'group_position', ['slug'], unique=False)
    op.create_table('job_experience',
    sa.Column('title', sa.String(length=50), nullable=False),
    sa.Column('from_year', sa.Integer(), nullable=False),
    sa.Column('to_year', sa.Integer(), nullable=False),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_job_experience_id'), 'job_experience', ['id'], unique=False)
    op.create_table('job_salary',
    sa.Column('salary', sa.Integer(), nullable=False),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('salary')
    )
    op.create_index(op.f('ix_job_salary_id'), 'job_salary', ['id'], unique=False)
    op.create_table('label_company',
    sa.Column('name', sa.String(length=10), nullable=False),
    sa.Column('description', sa.String(length=255), nullable=True),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_label_company_id'), 'label_company', ['id'], unique=False)
    op.create_table('manager_base',
    sa.Column('full_name', sa.String(length=50), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('hashed_password', sa.String(length=255), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('avatar', sa.String(length=255), nullable=True),
    sa.Column('role', sa.Enum('SUPER_USER', 'ADMIN', 'USER', 'SOCIAL_NETWORK', 'GUEST', 'BUSINESS', name='role'), nullable=True),
    sa.Column('type_account', sa.Enum('NORMAL', 'BUSINESS', name='typeaccount'), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('last_login', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_manager_base_email'), 'manager_base', ['email'], unique=True)
    op.create_index(op.f('ix_manager_base_id'), 'manager_base', ['id'], unique=False)
    op.create_table('province',
    sa.Column('name', sa.String(length=50), nullable=False),
    sa.Column('code', sa.String(length=10), nullable=True),
    sa.Column('name_with_type', sa.String(length=50), nullable=False),
    sa.Column('slug', sa.String(length=50), nullable=False),
    sa.Column('type', sa.String(length=50), nullable=False),
    sa.Column('country', sa.String(length=50), nullable=True),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_province_code'), 'province', ['code'], unique=True)
    op.create_index(op.f('ix_province_id'), 'province', ['id'], unique=False)
    op.create_index(op.f('ix_province_name'), 'province', ['name'], unique=True)
    op.create_index(op.f('ix_province_name_with_type'), 'province', ['name_with_type'], unique=True)
    op.create_index(op.f('ix_province_slug'), 'province', ['slug'], unique=True)
    op.create_table('skill',
    sa.Column('name', sa.String(length=50), nullable=False),
    sa.Column('slug', sa.String(length=50), nullable=False),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_skill_id'), 'skill', ['id'], unique=False)
    op.create_table('user',
    sa.Column('full_name', sa.String(length=50), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('hashed_password', sa.String(length=255), nullable=False),
    sa.Column('phone_number', sa.String(length=10), nullable=True),
    sa.Column('gender', sa.Enum('MALE', 'FEMALE', 'OTHER', name='gender'), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('role', sa.Enum('SUPER_USER', 'ADMIN', 'USER', 'SOCIAL_NETWORK', 'GUEST', 'BUSINESS', name='role'), nullable=True),
    sa.Column('is_verified', sa.Boolean(), nullable=True),
    sa.Column('avatar', sa.String(length=255), nullable=True),
    sa.Column('type_account', sa.Enum('NORMAL', 'BUSINESS', name='typeaccount'), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('last_login', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_user_email'), 'user', ['email'], unique=True)
    op.create_index(op.f('ix_user_id'), 'user', ['id'], unique=False)
    op.create_table('verify_code_block',
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_verify_code_block_id'), 'verify_code_block', ['id'], unique=False)
    op.create_table('work_market',
    sa.Column('quantity_company_recruitment', sa.Integer(), nullable=False),
    sa.Column('quantity_job_recruitment', sa.Integer(), nullable=False),
    sa.Column('quantity_job_recruitment_yesterday', sa.Integer(), nullable=False),
    sa.Column('quantity_job_new_today', sa.Integer(), nullable=False),
    sa.Column('time_scan', sa.DateTime(), nullable=False),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_work_market_id'), 'work_market', ['id'], unique=False)
    op.create_table('admin',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('is_verified', sa.Boolean(), nullable=True),
    sa.Column('phone_number', sa.String(length=10), nullable=False),
    sa.Column('gender', sa.Enum('MALE', 'FEMALE', 'OTHER', name='gender'), nullable=True),
    sa.ForeignKeyConstraint(['id'], ['manager_base.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_admin_id'), 'admin', ['id'], unique=False)
    op.create_table('district',
    sa.Column('name', sa.String(length=50), nullable=False),
    sa.Column('code', sa.String(length=10), nullable=True),
    sa.Column('name_with_type', sa.String(length=50), nullable=False),
    sa.Column('slug', sa.String(length=50), nullable=False),
    sa.Column('type', sa.String(length=20), nullable=False),
    sa.Column('province_id', sa.Integer(), nullable=False),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.ForeignKeyConstraint(['province_id'], ['province.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_district_code'), 'district', ['code'], unique=True)
    op.create_index(op.f('ix_district_id'), 'district', ['id'], unique=False)
    op.create_index(op.f('ix_district_name'), 'district', ['name'], unique=False)
    op.create_index(op.f('ix_district_name_with_type'), 'district', ['name_with_type'], unique=False)
    op.create_index(op.f('ix_district_slug'), 'district', ['slug'], unique=False)
    op.create_table('job_position',
    sa.Column('name', sa.String(length=50), nullable=False),
    sa.Column('slug', sa.String(length=50), nullable=False),
    sa.Column('count', sa.Integer(), nullable=True),
    sa.Column('group_position_id', sa.Integer(), nullable=True),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.ForeignKeyConstraint(['group_position_id'], ['group_position.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_job_position_id'), 'job_position', ['id'], unique=False)
    op.create_table('social_network',
    sa.Column('type', sa.Enum('GOOGLE', 'FACEBOOK', 'GITHUB', 'TWITTER', 'LINKEDIN', name='provider'), nullable=False),
    sa.Column('social_id', sa.String(length=50), nullable=False),
    sa.Column('full_name', sa.String(length=50), nullable=True),
    sa.Column('phone_number', sa.String(length=10), nullable=True),
    sa.Column('avatar', sa.String(length=255), nullable=True),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('access_token', sa.String(length=500), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('role', sa.Enum('SUPER_USER', 'ADMIN', 'USER', 'SOCIAL_NETWORK', 'GUEST', 'BUSINESS', name='role'), nullable=True),
    sa.Column('is_verified', sa.Boolean(), nullable=True),
    sa.Column('type_account', sa.Enum('NORMAL', 'BUSINESS', name='typeaccount'), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('last_login', sa.DateTime(timezone=True), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_social_network_id'), 'social_network', ['id'], unique=False)
    op.create_index(op.f('ix_social_network_type'), 'social_network', ['type'], unique=False)
    op.create_table('user_job_requirement',
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('job_salary_id', sa.Integer(), nullable=True),
    sa.Column('job_experience_id', sa.Integer(), nullable=True),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.ForeignKeyConstraint(['job_experience_id'], ['job_experience.id'], ),
    sa.ForeignKeyConstraint(['job_salary_id'], ['job_salary.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_user_job_requirement_id'), 'user_job_requirement', ['id'], unique=False)
    op.create_index(op.f('ix_user_job_requirement_user_id'), 'user_job_requirement', ['user_id'], unique=False)
    op.create_table('verify_code',
    sa.Column('code', sa.String(length=6), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('status', sa.Enum('ACTIVE', 'INACTIVE', name='verifycodestatus'), nullable=True),
    sa.Column('failed_attempts', sa.Integer(), nullable=False),
    sa.Column('session_id', sa.String(length=255), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('expired_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('manager_base_id', sa.Integer(), nullable=False),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.ForeignKeyConstraint(['manager_base_id'], ['manager_base.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_verify_code_expired_at'), 'verify_code', ['expired_at'], unique=False)
    op.create_index(op.f('ix_verify_code_id'), 'verify_code', ['id'], unique=False)
    op.create_index(op.f('ix_verify_code_session_id'), 'verify_code', ['session_id'], unique=False)
    op.create_table('business',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('province_id', sa.Integer(), nullable=False),
    sa.Column('district_id', sa.Integer(), nullable=True),
    sa.Column('phone_number', sa.String(length=10), nullable=False),
    sa.Column('gender', sa.Enum('MALE', 'FEMALE', 'OTHER', name='gender'), nullable=False),
    sa.Column('company_name', sa.String(length=255), nullable=False),
    sa.Column('work_position', sa.String(length=100), nullable=False),
    sa.Column('work_location', sa.String(length=100), nullable=True),
    sa.Column('is_verified_email', sa.Boolean(), nullable=True),
    sa.Column('is_verified_phone', sa.Boolean(), nullable=True),
    sa.Column('is_verified_company', sa.Boolean(), nullable=True),
    sa.Column('is_verified_identity', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['district_id'], ['district.id'], ),
    sa.ForeignKeyConstraint(['id'], ['manager_base.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['province_id'], ['province.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_business_id'), 'business', ['id'], unique=False)
    op.create_table('user_job_requirement_category',
    sa.Column('category_id', sa.Integer(), nullable=True),
    sa.Column('user_job_requirement_id', sa.Integer(), nullable=True),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.ForeignKeyConstraint(['category_id'], ['category.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_job_requirement_id'], ['user_job_requirement.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_user_job_requirement_category_category_id'), 'user_job_requirement_category', ['category_id'], unique=False)
    op.create_index(op.f('ix_user_job_requirement_category_id'), 'user_job_requirement_category', ['id'], unique=False)
    op.create_index(op.f('ix_user_job_requirement_category_user_job_requirement_id'), 'user_job_requirement_category', ['user_job_requirement_id'], unique=False)
    op.create_table('user_job_requirement_location',
    sa.Column('province_id', sa.Integer(), nullable=False),
    sa.Column('district_id', sa.Integer(), nullable=True),
    sa.Column('user_job_requirement_id', sa.Integer(), nullable=False),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.ForeignKeyConstraint(['district_id'], ['district.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['province_id'], ['province.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_job_requirement_id'], ['user_job_requirement.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_user_job_requirement_location_district_id'), 'user_job_requirement_location', ['district_id'], unique=False)
    op.create_index(op.f('ix_user_job_requirement_location_id'), 'user_job_requirement_location', ['id'], unique=False)
    op.create_index(op.f('ix_user_job_requirement_location_province_id'), 'user_job_requirement_location', ['province_id'], unique=False)
    op.create_index(op.f('ix_user_job_requirement_location_user_job_requirement_id'), 'user_job_requirement_location', ['user_job_requirement_id'], unique=False)
    op.create_table('user_job_requirement_position',
    sa.Column('user_job_requirement_id', sa.Integer(), nullable=True),
    sa.Column('job_position_id', sa.Integer(), nullable=True),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.ForeignKeyConstraint(['job_position_id'], ['job_position.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_job_requirement_id'], ['user_job_requirement.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_user_job_requirement_position_id'), 'user_job_requirement_position', ['id'], unique=False)
    op.create_index(op.f('ix_user_job_requirement_position_job_position_id'), 'user_job_requirement_position', ['job_position_id'], unique=False)
    op.create_index(op.f('ix_user_job_requirement_position_user_job_requirement_id'), 'user_job_requirement_position', ['user_job_requirement_id'], unique=False)
    op.create_table('user_job_requirement_skill',
    sa.Column('user_job_requirement_id', sa.Integer(), nullable=True),
    sa.Column('skill_id', sa.Integer(), nullable=True),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.ForeignKeyConstraint(['skill_id'], ['skill.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_job_requirement_id'], ['user_job_requirement.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_user_job_requirement_skill_id'), 'user_job_requirement_skill', ['id'], unique=False)
    op.create_index(op.f('ix_user_job_requirement_skill_skill_id'), 'user_job_requirement_skill', ['skill_id'], unique=False)
    op.create_index(op.f('ix_user_job_requirement_skill_user_job_requirement_id'), 'user_job_requirement_skill', ['user_job_requirement_id'], unique=False)
    op.create_table('business_history',
    sa.Column('business_id', sa.Integer(), nullable=True),
    sa.Column('content', sa.String(length=255), nullable=False),
    sa.Column('type', sa.Enum('REGISTER', 'LOGIN', 'VERIFY_SUCCESS', 'CREATE_NEW_CAMPAIGN', 'OFF_CAMPAIGN', 'ON_CAMPAIGN', 'DELETE_CAMPAIGN', 'UPDATE_CAMPAIGN', 'APPROVE_JOB', 'REJECT_JOB', name='historytype'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.ForeignKeyConstraint(['business_id'], ['business.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_business_history_business_id'), 'business_history', ['business_id'], unique=False)
    op.create_index(op.f('ix_business_history_id'), 'business_history', ['id'], unique=False)
    op.create_table('company',
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('type', sa.Enum('COMPANY', 'BUSINESS', name='companytype'), nullable=False),
    sa.Column('address', sa.String(length=255), nullable=False),
    sa.Column('phone_number', sa.String(length=10), nullable=False),
    sa.Column('logo', sa.String(length=255), nullable=True),
    sa.Column('banner', sa.String(length=255), nullable=True),
    sa.Column('total_active_jobs', sa.Integer(), nullable=True),
    sa.Column('is_premium', sa.Boolean(), nullable=True),
    sa.Column('is_verified', sa.Boolean(), nullable=True),
    sa.Column('label_company_id', sa.Integer(), nullable=True),
    sa.Column('website', sa.String(length=255), nullable=True),
    sa.Column('scale', sa.String(length=20), nullable=False),
    sa.Column('tax_code', sa.String(length=15), nullable=False),
    sa.Column('company_short_description', sa.Text(), nullable=True),
    sa.Column('follower', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('business_id', sa.Integer(), nullable=False),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.ForeignKeyConstraint(['business_id'], ['business.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['label_company_id'], ['label_company.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_company_email'), 'company', ['email'], unique=True)
    op.create_index(op.f('ix_company_id'), 'company', ['id'], unique=False)
    op.create_index(op.f('ix_company_name'), 'company', ['name'], unique=False)
    op.create_index(op.f('ix_company_tax_code'), 'company', ['tax_code'], unique=True)
    op.create_table('campaign',
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('status', sa.Enum('STOPPED', 'OPEN', name='campaignstatus'), nullable=True),
    sa.Column('is_flash', sa.Boolean(), nullable=True),
    sa.Column('optimal_score', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('business_id', sa.Integer(), nullable=False),
    sa.Column('company_id', sa.Integer(), nullable=False),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.ForeignKeyConstraint(['business_id'], ['business.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['company_id'], ['company.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_campaign_company_id'), 'campaign', ['company_id'], unique=False)
    op.create_index(op.f('ix_campaign_id'), 'campaign', ['id'], unique=False)
    op.create_table('company_business',
    sa.Column('business_id', sa.Integer(), nullable=True),
    sa.Column('company_id', sa.Integer(), nullable=True),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.ForeignKeyConstraint(['business_id'], ['business.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['company_id'], ['company.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_company_business_id'), 'company_business', ['id'], unique=False)
    op.create_table('company_field',
    sa.Column('company_id', sa.Integer(), nullable=True),
    sa.Column('field_id', sa.Integer(), nullable=True),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.ForeignKeyConstraint(['company_id'], ['company.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['field_id'], ['field.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_company_field_company_id'), 'company_field', ['company_id'], unique=False)
    op.create_index(op.f('ix_company_field_field_id'), 'company_field', ['field_id'], unique=False)
    op.create_index(op.f('ix_company_field_id'), 'company_field', ['id'], unique=False)
    op.create_table('job',
    sa.Column('business_id', sa.Integer(), nullable=False),
    sa.Column('campaign_id', sa.Integer(), nullable=False),
    sa.Column('job_experience_id', sa.Integer(), nullable=False),
    sa.Column('job_position_id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('job_description', sa.Text(), nullable=False),
    sa.Column('job_requirement', sa.Text(), nullable=False),
    sa.Column('job_benefit', sa.Text(), nullable=False),
    sa.Column('job_location', sa.String(length=255), nullable=False),
    sa.Column('max_salary', sa.Integer(), nullable=True),
    sa.Column('min_salary', sa.Integer(), nullable=True),
    sa.Column('salary_type', sa.Enum('VND', 'USD', 'DEAL', name='salarytype'), nullable=False),
    sa.Column('quantity', sa.Integer(), nullable=False),
    sa.Column('full_name_contact', sa.String(length=50), nullable=False),
    sa.Column('phone_number_contact', sa.String(length=10), nullable=False),
    sa.Column('email_contact', sa.JSON(), nullable=False),
    sa.Column('status', sa.Enum('PENDING', 'PUBLISHED', 'REJECTED', 'EXPIRED', 'DRAFT', 'BANNED', 'STOPPED', name='jobstatus'), nullable=True),
    sa.Column('employment_type', sa.Enum('FULL_TIME', 'PART_TIME', 'INTERNSHIP', name='jobtype'), nullable=True),
    sa.Column('gender_requirement', sa.Enum('MALE', 'FEMALE', 'OTHER', name='gender'), nullable=True),
    sa.Column('deadline', sa.Date(), nullable=False),
    sa.Column('employer_verified', sa.Boolean(), nullable=True),
    sa.Column('is_featured', sa.Boolean(), nullable=True),
    sa.Column('is_highlight', sa.Boolean(), nullable=True),
    sa.Column('is_urgent', sa.Boolean(), nullable=True),
    sa.Column('is_paid_featured', sa.Boolean(), nullable=True),
    sa.Column('is_bg_featured', sa.Boolean(), nullable=True),
    sa.Column('is_vip_employer', sa.Boolean(), nullable=True),
    sa.Column('is_diamond_employer', sa.Boolean(), nullable=True),
    sa.Column('is_job_flash', sa.Boolean(), nullable=True),
    sa.Column('working_time_text', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.ForeignKeyConstraint(['business_id'], ['business.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['campaign_id'], ['campaign.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['job_experience_id'], ['job_experience.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_job_campaign_id'), 'job', ['campaign_id'], unique=False)
    op.create_index(op.f('ix_job_deadline'), 'job', ['deadline'], unique=False)
    op.create_index(op.f('ix_job_employment_type'), 'job', ['employment_type'], unique=False)
    op.create_index(op.f('ix_job_gender_requirement'), 'job', ['gender_requirement'], unique=False)
    op.create_index(op.f('ix_job_id'), 'job', ['id'], unique=False)
    op.create_index(op.f('ix_job_job_experience_id'), 'job', ['job_experience_id'], unique=False)
    op.create_index(op.f('ix_job_job_position_id'), 'job', ['job_position_id'], unique=False)
    op.create_index(op.f('ix_job_max_salary'), 'job', ['max_salary'], unique=False)
    op.create_index(op.f('ix_job_min_salary'), 'job', ['min_salary'], unique=False)
    op.create_index(op.f('ix_job_quantity'), 'job', ['quantity'], unique=False)
    op.create_index(op.f('ix_job_salary_type'), 'job', ['salary_type'], unique=False)
    op.create_index(op.f('ix_job_status'), 'job', ['status'], unique=False)
    op.create_index(op.f('ix_job_title'), 'job', ['title'], unique=False)
    op.create_table('c_v_application',
    sa.Column('job_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('cv', sa.String(length=255), nullable=False),
    sa.Column('full_name', sa.String(length=50), nullable=False),
    sa.Column('email', sa.String(length=50), nullable=False),
    sa.Column('phone_number', sa.String(length=10), nullable=False),
    sa.Column('letter_cover', sa.String(length=500), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.ForeignKeyConstraint(['job_id'], ['job.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_c_v_application_id'), 'c_v_application', ['id'], unique=False)
    op.create_index(op.f('ix_c_v_application_job_id'), 'c_v_application', ['job_id'], unique=False)
    op.create_index(op.f('ix_c_v_application_user_id'), 'c_v_application', ['user_id'], unique=False)
    op.create_table('job_approval_request',
    sa.Column('job_id', sa.Integer(), nullable=True),
    sa.Column('status', sa.Enum('PENDING', 'APPROVED', 'REJECTED', 'STOPPED', name='jobapprovalstatus'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.ForeignKeyConstraint(['job_id'], ['job.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_job_approval_request_created_at'), 'job_approval_request', ['created_at'], unique=False)
    op.create_index(op.f('ix_job_approval_request_id'), 'job_approval_request', ['id'], unique=False)
    op.create_index(op.f('ix_job_approval_request_job_id'), 'job_approval_request', ['job_id'], unique=False)
    op.create_index(op.f('ix_job_approval_request_status'), 'job_approval_request', ['status'], unique=False)
    op.create_index(op.f('ix_job_approval_request_updated_at'), 'job_approval_request', ['updated_at'], unique=False)
    op.create_table('job_category',
    sa.Column('job_id', sa.Integer(), nullable=True),
    sa.Column('category_id', sa.Integer(), nullable=True),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.ForeignKeyConstraint(['category_id'], ['category.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['job_id'], ['job.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_job_category_category_id'), 'job_category', ['category_id'], unique=False)
    op.create_index(op.f('ix_job_category_id'), 'job_category', ['id'], unique=False)
    op.create_index(op.f('ix_job_category_job_id'), 'job_category', ['job_id'], unique=False)
    op.create_table('job_report',
    sa.Column('job_id', sa.Integer(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('report_type', sa.String(length=10), nullable=True),
    sa.Column('report_content', sa.String(length=100), nullable=True),
    sa.Column('report_status', sa.String(length=10), nullable=True),
    sa.Column('report_created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('report_updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.ForeignKeyConstraint(['job_id'], ['job.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_job_report_id'), 'job_report', ['id'], unique=False)
    op.create_index(op.f('ix_job_report_job_id'), 'job_report', ['job_id'], unique=False)
    op.create_index(op.f('ix_job_report_report_content'), 'job_report', ['report_content'], unique=False)
    op.create_index(op.f('ix_job_report_report_created_at'), 'job_report', ['report_created_at'], unique=False)
    op.create_index(op.f('ix_job_report_report_status'), 'job_report', ['report_status'], unique=False)
    op.create_index(op.f('ix_job_report_report_type'), 'job_report', ['report_type'], unique=False)
    op.create_index(op.f('ix_job_report_report_updated_at'), 'job_report', ['report_updated_at'], unique=False)
    op.create_index(op.f('ix_job_report_user_id'), 'job_report', ['user_id'], unique=False)
    op.create_table('job_skill',
    sa.Column('job_id', sa.Integer(), nullable=True),
    sa.Column('skill_id', sa.Integer(), nullable=True),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.ForeignKeyConstraint(['job_id'], ['job.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['skill_id'], ['skill.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_job_skill_id'), 'job_skill', ['id'], unique=False)
    op.create_index(op.f('ix_job_skill_job_id'), 'job_skill', ['job_id'], unique=False)
    op.create_index(op.f('ix_job_skill_skill_id'), 'job_skill', ['skill_id'], unique=False)
    op.create_table('user_job_save',
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('job_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.ForeignKeyConstraint(['job_id'], ['job.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_user_job_save_id'), 'user_job_save', ['id'], unique=False)
    op.create_index(op.f('ix_user_job_save_job_id'), 'user_job_save', ['job_id'], unique=False)
    op.create_index(op.f('ix_user_job_save_user_id'), 'user_job_save', ['user_id'], unique=False)
    op.create_table('work_location',
    sa.Column('job_id', sa.Integer(), nullable=True),
    sa.Column('province_id', sa.Integer(), nullable=False),
    sa.Column('district_id', sa.Integer(), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.ForeignKeyConstraint(['district_id'], ['district.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['job_id'], ['job.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['province_id'], ['province.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_work_location_district_id'), 'work_location', ['district_id'], unique=False)
    op.create_index(op.f('ix_work_location_id'), 'work_location', ['id'], unique=False)
    op.create_index(op.f('ix_work_location_job_id'), 'work_location', ['job_id'], unique=False)
    op.create_index(op.f('ix_work_location_province_id'), 'work_location', ['province_id'], unique=False)
    op.create_table('working_time',
    sa.Column('job_id', sa.Integer(), nullable=True),
    sa.Column('start_time', sa.Time(), nullable=False),
    sa.Column('end_time', sa.Time(), nullable=False),
    sa.Column('date_from', sa.Integer(), nullable=False),
    sa.Column('date_to', sa.Integer(), nullable=False),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.ForeignKeyConstraint(['job_id'], ['job.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_working_time_id'), 'working_time', ['id'], unique=False)
    op.create_index(op.f('ix_working_time_job_id'), 'working_time', ['job_id'], unique=False)
    op.create_table('approval_log',
    sa.Column('job_approval_request_id', sa.Integer(), nullable=True),
    sa.Column('admin_id', sa.Integer(), nullable=True),
    sa.Column('previous_status', sa.Enum('PENDING', 'APPROVED', 'REJECTED', 'STOPPED', name='jobapprovalstatus'), nullable=False),
    sa.Column('new_status', sa.Enum('PENDING', 'APPROVED', 'REJECTED', 'STOPPED', name='jobapprovalstatus'), nullable=False),
    sa.Column('reason', sa.String(length=100), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.ForeignKeyConstraint(['admin_id'], ['admin.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['job_approval_request_id'], ['job_approval_request.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_approval_log_admin_id'), 'approval_log', ['admin_id'], unique=False)
    op.create_index(op.f('ix_approval_log_id'), 'approval_log', ['id'], unique=False)
    op.create_index(op.f('ix_approval_log_job_approval_request_id'), 'approval_log', ['job_approval_request_id'], unique=False)
    op.create_index(op.f('ix_approval_log_new_status'), 'approval_log', ['new_status'], unique=False)
    op.create_index(op.f('ix_approval_log_previous_status'), 'approval_log', ['previous_status'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_approval_log_previous_status'), table_name='approval_log')
    op.drop_index(op.f('ix_approval_log_new_status'), table_name='approval_log')
    op.drop_index(op.f('ix_approval_log_job_approval_request_id'), table_name='approval_log')
    op.drop_index(op.f('ix_approval_log_id'), table_name='approval_log')
    op.drop_index(op.f('ix_approval_log_admin_id'), table_name='approval_log')
    op.drop_table('approval_log')
    op.drop_index(op.f('ix_working_time_job_id'), table_name='working_time')
    op.drop_index(op.f('ix_working_time_id'), table_name='working_time')
    op.drop_table('working_time')
    op.drop_index(op.f('ix_work_location_province_id'), table_name='work_location')
    op.drop_index(op.f('ix_work_location_job_id'), table_name='work_location')
    op.drop_index(op.f('ix_work_location_id'), table_name='work_location')
    op.drop_index(op.f('ix_work_location_district_id'), table_name='work_location')
    op.drop_table('work_location')
    op.drop_index(op.f('ix_user_job_save_user_id'), table_name='user_job_save')
    op.drop_index(op.f('ix_user_job_save_job_id'), table_name='user_job_save')
    op.drop_index(op.f('ix_user_job_save_id'), table_name='user_job_save')
    op.drop_table('user_job_save')
    op.drop_index(op.f('ix_job_skill_skill_id'), table_name='job_skill')
    op.drop_index(op.f('ix_job_skill_job_id'), table_name='job_skill')
    op.drop_index(op.f('ix_job_skill_id'), table_name='job_skill')
    op.drop_table('job_skill')
    op.drop_index(op.f('ix_job_report_user_id'), table_name='job_report')
    op.drop_index(op.f('ix_job_report_report_updated_at'), table_name='job_report')
    op.drop_index(op.f('ix_job_report_report_type'), table_name='job_report')
    op.drop_index(op.f('ix_job_report_report_status'), table_name='job_report')
    op.drop_index(op.f('ix_job_report_report_created_at'), table_name='job_report')
    op.drop_index(op.f('ix_job_report_report_content'), table_name='job_report')
    op.drop_index(op.f('ix_job_report_job_id'), table_name='job_report')
    op.drop_index(op.f('ix_job_report_id'), table_name='job_report')
    op.drop_table('job_report')
    op.drop_index(op.f('ix_job_category_job_id'), table_name='job_category')
    op.drop_index(op.f('ix_job_category_id'), table_name='job_category')
    op.drop_index(op.f('ix_job_category_category_id'), table_name='job_category')
    op.drop_table('job_category')
    op.drop_index(op.f('ix_job_approval_request_updated_at'), table_name='job_approval_request')
    op.drop_index(op.f('ix_job_approval_request_status'), table_name='job_approval_request')
    op.drop_index(op.f('ix_job_approval_request_job_id'), table_name='job_approval_request')
    op.drop_index(op.f('ix_job_approval_request_id'), table_name='job_approval_request')
    op.drop_index(op.f('ix_job_approval_request_created_at'), table_name='job_approval_request')
    op.drop_table('job_approval_request')
    op.drop_index(op.f('ix_c_v_application_user_id'), table_name='c_v_application')
    op.drop_index(op.f('ix_c_v_application_job_id'), table_name='c_v_application')
    op.drop_index(op.f('ix_c_v_application_id'), table_name='c_v_application')
    op.drop_table('c_v_application')
    op.drop_index(op.f('ix_job_title'), table_name='job')
    op.drop_index(op.f('ix_job_status'), table_name='job')
    op.drop_index(op.f('ix_job_salary_type'), table_name='job')
    op.drop_index(op.f('ix_job_quantity'), table_name='job')
    op.drop_index(op.f('ix_job_min_salary'), table_name='job')
    op.drop_index(op.f('ix_job_max_salary'), table_name='job')
    op.drop_index(op.f('ix_job_job_position_id'), table_name='job')
    op.drop_index(op.f('ix_job_job_experience_id'), table_name='job')
    op.drop_index(op.f('ix_job_id'), table_name='job')
    op.drop_index(op.f('ix_job_gender_requirement'), table_name='job')
    op.drop_index(op.f('ix_job_employment_type'), table_name='job')
    op.drop_index(op.f('ix_job_deadline'), table_name='job')
    op.drop_index(op.f('ix_job_campaign_id'), table_name='job')
    op.drop_table('job')
    op.drop_index(op.f('ix_company_field_id'), table_name='company_field')
    op.drop_index(op.f('ix_company_field_field_id'), table_name='company_field')
    op.drop_index(op.f('ix_company_field_company_id'), table_name='company_field')
    op.drop_table('company_field')
    op.drop_index(op.f('ix_company_business_id'), table_name='company_business')
    op.drop_table('company_business')
    op.drop_index(op.f('ix_campaign_id'), table_name='campaign')
    op.drop_index(op.f('ix_campaign_company_id'), table_name='campaign')
    op.drop_table('campaign')
    op.drop_index(op.f('ix_company_tax_code'), table_name='company')
    op.drop_index(op.f('ix_company_name'), table_name='company')
    op.drop_index(op.f('ix_company_id'), table_name='company')
    op.drop_index(op.f('ix_company_email'), table_name='company')
    op.drop_table('company')
    op.drop_index(op.f('ix_business_history_id'), table_name='business_history')
    op.drop_index(op.f('ix_business_history_business_id'), table_name='business_history')
    op.drop_table('business_history')
    op.drop_index(op.f('ix_user_job_requirement_skill_user_job_requirement_id'), table_name='user_job_requirement_skill')
    op.drop_index(op.f('ix_user_job_requirement_skill_skill_id'), table_name='user_job_requirement_skill')
    op.drop_index(op.f('ix_user_job_requirement_skill_id'), table_name='user_job_requirement_skill')
    op.drop_table('user_job_requirement_skill')
    op.drop_index(op.f('ix_user_job_requirement_position_user_job_requirement_id'), table_name='user_job_requirement_position')
    op.drop_index(op.f('ix_user_job_requirement_position_job_position_id'), table_name='user_job_requirement_position')
    op.drop_index(op.f('ix_user_job_requirement_position_id'), table_name='user_job_requirement_position')
    op.drop_table('user_job_requirement_position')
    op.drop_index(op.f('ix_user_job_requirement_location_user_job_requirement_id'), table_name='user_job_requirement_location')
    op.drop_index(op.f('ix_user_job_requirement_location_province_id'), table_name='user_job_requirement_location')
    op.drop_index(op.f('ix_user_job_requirement_location_id'), table_name='user_job_requirement_location')
    op.drop_index(op.f('ix_user_job_requirement_location_district_id'), table_name='user_job_requirement_location')
    op.drop_table('user_job_requirement_location')
    op.drop_index(op.f('ix_user_job_requirement_category_user_job_requirement_id'), table_name='user_job_requirement_category')
    op.drop_index(op.f('ix_user_job_requirement_category_id'), table_name='user_job_requirement_category')
    op.drop_index(op.f('ix_user_job_requirement_category_category_id'), table_name='user_job_requirement_category')
    op.drop_table('user_job_requirement_category')
    op.drop_index(op.f('ix_business_id'), table_name='business')
    op.drop_table('business')
    op.drop_index(op.f('ix_verify_code_session_id'), table_name='verify_code')
    op.drop_index(op.f('ix_verify_code_id'), table_name='verify_code')
    op.drop_index(op.f('ix_verify_code_expired_at'), table_name='verify_code')
    op.drop_table('verify_code')
    op.drop_index(op.f('ix_user_job_requirement_user_id'), table_name='user_job_requirement')
    op.drop_index(op.f('ix_user_job_requirement_id'), table_name='user_job_requirement')
    op.drop_table('user_job_requirement')
    op.drop_index(op.f('ix_social_network_type'), table_name='social_network')
    op.drop_index(op.f('ix_social_network_id'), table_name='social_network')
    op.drop_table('social_network')
    op.drop_index(op.f('ix_job_position_id'), table_name='job_position')
    op.drop_table('job_position')
    op.drop_index(op.f('ix_district_slug'), table_name='district')
    op.drop_index(op.f('ix_district_name_with_type'), table_name='district')
    op.drop_index(op.f('ix_district_name'), table_name='district')
    op.drop_index(op.f('ix_district_id'), table_name='district')
    op.drop_index(op.f('ix_district_code'), table_name='district')
    op.drop_table('district')
    op.drop_index(op.f('ix_admin_id'), table_name='admin')
    op.drop_table('admin')
    op.drop_index(op.f('ix_work_market_id'), table_name='work_market')
    op.drop_table('work_market')
    op.drop_index(op.f('ix_verify_code_block_id'), table_name='verify_code_block')
    op.drop_table('verify_code_block')
    op.drop_index(op.f('ix_user_id'), table_name='user')
    op.drop_index(op.f('ix_user_email'), table_name='user')
    op.drop_table('user')
    op.drop_index(op.f('ix_skill_id'), table_name='skill')
    op.drop_table('skill')
    op.drop_index(op.f('ix_province_slug'), table_name='province')
    op.drop_index(op.f('ix_province_name_with_type'), table_name='province')
    op.drop_index(op.f('ix_province_name'), table_name='province')
    op.drop_index(op.f('ix_province_id'), table_name='province')
    op.drop_index(op.f('ix_province_code'), table_name='province')
    op.drop_table('province')
    op.drop_index(op.f('ix_manager_base_id'), table_name='manager_base')
    op.drop_index(op.f('ix_manager_base_email'), table_name='manager_base')
    op.drop_table('manager_base')
    op.drop_index(op.f('ix_label_company_id'), table_name='label_company')
    op.drop_table('label_company')
    op.drop_index(op.f('ix_job_salary_id'), table_name='job_salary')
    op.drop_table('job_salary')
    op.drop_index(op.f('ix_job_experience_id'), table_name='job_experience')
    op.drop_table('job_experience')
    op.drop_index(op.f('ix_group_position_slug'), table_name='group_position')
    op.drop_index(op.f('ix_group_position_name'), table_name='group_position')
    op.drop_index(op.f('ix_group_position_id'), table_name='group_position')
    op.drop_table('group_position')
    op.drop_index(op.f('ix_field_id'), table_name='field')
    op.drop_table('field')
    op.drop_index(op.f('ix_cruitment_demand_id'), table_name='cruitment_demand')
    op.drop_table('cruitment_demand')
    op.drop_index(op.f('ix_category_id'), table_name='category')
    op.drop_table('category')
    op.drop_index(op.f('ix_blacklist_token'), table_name='blacklist')
    op.drop_index(op.f('ix_blacklist_id'), table_name='blacklist')
    op.drop_table('blacklist')
    # ### end Alembic commands ###
